version: "3"

services:
  app:
    build: .
    image: clubecuritibano/agendamendo-golfe-api:app
    container_name: Agendamento-Golfe-API
    network_mode: bridge
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    command: node ace serve --watch
    env_file:
      - .env
