version: "3"

services:
  app:
    build: .
    image: clubecuritibano/golfe-api-adonis:app
    container_name: Golfe-API-Adonis
    network_mode: bridge
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    command: node ace serve --watch
    env_file:
      - .env
